name: Deploy to Production

on:
  push:
    branches: [ main ]
  # pull_request は削除（テスト用の別ワークフローを作成推奨）

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json, pdo

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install --no-dev --optimize-autoloader --no-ansi --no-interaction --no-progress --prefer-dist

    # 本番環境では事前設定済みのAPP_KEYを使用（削除または条件付き実行）
    # - name: Generate key
    #   run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 755 storage bootstrap/cache

    - name: Clear Laravel Caches
      run: |
        php artisan config:clear
        php artisan cache:clear
        php artisan view:clear

    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: sv14052.xserver.jp
        username: yoshida@kiryu-factory.com
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /kiryu-factory.com/public_html/koutei/
        local-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env
          **/.env.example
          **/tests/**
          **/.github/**
